USE master
GO
IF DB_ID (N'QUANLY_BANHANG')IS NOT NULL
DROP DATABASE QuanLy_BanHang
GO
CREATE DATABASE QUANLY_BANHANG
GO
USE QUANLY_BANHANG
GO
CREATE TABLE LOAISANPHAM
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(100)
	)
GO
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'APPLE')
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'BOSE')
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'GRADO')
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'MARSHALL')
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'HARMAN KARDON')
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'SKULLCANDY')
INSERT INTO LOAISANPHAM(TENLOAI) VALUES(N'SONY')
GO
CREATE TABLE SANPHAM
(
	MASP INT IDENTITY(1,1) PRIMARY KEY,
	TENSP NVARCHAR(100),
	GIA DECIMAL(20,2),
	HINH NVARCHAR(250),
	MALOAI INT FOREIGN KEY REFERENCES LOAISANPHAM(MALOAI),
	CHITIET NVARCHAR(MAX)
)
GO
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'APPLE EARPODS WITH REMOTE AND MIC',890000,N'01.jpg',1)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BLUETOOTH BOSE QUIETCOMFORT 35',8990000,N'02.jpg',2)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BOSE QC 25 FOR APPLE',7870000,N'03.jpg',2)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BOSE QUIETCOMFORT 3 ACOUSTIC NOISE CANCELLING',7900000,N'04.jpg',2)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BOSE SOUNDLINK ON-EAR',7100000,N'05.jpg',2)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BOSE SOUNDTRUE AROUND-EAR II CHO APPLE',4880000,N'06.jpg',2)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BOSE SOUNDTRUE AROUND-EAR II CHO ANDROID',4880000,N'07.jpg',2)

INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO GS1000E',25420000,N'08.jpg',3)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO PS500E',15210000,N'09.jpg',3)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO PS1000E',42450000,N'10.jpg',3)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO RS1E',17690000,N'11.jpg',3)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO RS2E',12790000,N'12.jpg',3)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO SR225E',5320000,N'13.jpg',3)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'GRADO SR325E',7690000,N'14.jpg',3)

INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'MARSHALL MAJOR 2',2990000,N'15.jpg',4)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'MARSHALL MODE-EQ',2450000,N'16.jpg',4)

INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'HARMAN KARDON SOHO BT (BLUETOOTH)',6250000,N'17.jpg',5)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'HARMAN KARDON SOHO I(IOS)',3990000,N'18.jpg',5)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'HARMAN KARDON SOHO',3990000,N'19.jpg',5)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'HARMAN KARDON NI (NOISE-ISOLATING)',1390000,N'20.jpg',5)

INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY MIX MASTER (DJ) WITH MIC',7490000,N'21.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY CRUSHER WITH MIC',3099000,N'22.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY NAVIGATOR',2780000,N'23.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY AVIATOR WITH MIC3',2780000,N'24.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY HESH 2 WITH MIC',1890000,N'25.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY HESH 2',1680000,N'26.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'BLUETOOTH SKULLCANDY UPROAR WIRELESS',1450000,N'27.jpg',6)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SKULLCANDY GRIND',1390000,N'28.jpg',6)

INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY MDR-Z7',1599000,N'29.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY XBA-Z5',1399000,N'30.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY MDR-1R NOISE CANCELLING MK2',5518500,N'31.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY MDR-1ABT',8490000,N'32.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY MDR-1ADAC',7990000,N'33.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY H.EAR ON WIRELESS MDR-100ABN',7490000,N'34.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY XBA-A3',6990000,N'35.jpg',7)
INSERT INTO SANPHAM(TENSP,GIA,HINH,MALOAI) VALUES(N'SONY XBA-H3',6490000,N'36.jpg',7)
GO
CREATE TABLE LOGINADMIN
(
	MALOGIN INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50)
)
GO
INSERT INTO LOGINADMIN(USERNAME,PASSWORD) VALUES('ADMIN', '1234')
ALTER TABLE LOGINADMIN
ADD UNIQUE (USERNAME)
GO
CREATE TABLE LIENHE
(
	MALH INT IDENTITY(1,1) PRIMARY KEY,
	TENKH NVARCHAR(100),
	DTHOAI VARCHAR(15),
	EMAIL VARCHAR(50),
	NOIDUNG NVARCHAR(MAX)
)
GO
CREATE TABLE LOGINKHACHHANG
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY,
	HOTENKH NVARCHAR(50),
	DIACHIKH NVARCHAR(50),
	DIENTHOAIKH VARCHAR(10),
	TENDN VARCHAR(15),
	MATKHAU VARCHAR(15),
	NGAYSINH SMALLDATETIME,
	GIOITINH BIT,
	EMAIL VARCHAR(50),
)
GO
INSERT INTO LOGINKHACHHANG(HOTENKH,DIACHIKH,DIENTHOAIKH,TENDN,MATKHAU,NGAYSINH,GIOITINH,EMAIL) VALUES(N'USER',N'TDM','123456789','KAIS','KAIS','10/27/2016',1,'USER@GMAIL.COM')

--SELECT MAKH,HOTENKH,DIACHIKH,DIENTHOAIKH,EMAIL FROM LOGINKHACHHANG WHERE TENDN = 'ADMIN'

CREATE TABLE DONDATHANG 
(
	SOHD INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT FOREIGN KEY REFERENCES LOGINKHACHHANG(MAKH),
	NGAYDH SMALLDATETIME,
	NGAYGIAOHANG SMALLDATETIME,
	TENNGUOINHAN NVARCHAR(50),
	DIACHINHAN NVARCHAR(200),
	DIENTHOAINHAN VARCHAR(15),
)
GO
CREATE TABLE CTDATHANG
(
	SOHD INT FOREIGN KEY REFERENCES DONDATHANG(SOHD),
	MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
	SOLUONG INT,
	GIA DECIMAL(20,2), 
	THANHTIEN DECIMAL(20,2),
	CONSTRAINT PK PRIMARY KEY (SOHD,MASP)
)
GO
ALTER TABLE LOGINKHACHHANG
ADD UNIQUE (TENDN)
GO
ALTER TABLE LOGINKHACHHANG
ALTER COLUMN DIENTHOAIKH VARCHAR(15)
GO
ALTER TABLE LOGINKHACHHANG
ALTER COLUMN MATKHAU VARCHAR(15) NOT NULL
GO
ALTER TABLE DONDATHANG
ADD THANHCONG BIT
--SELECT * FROM DONDATHANG
--SELECT * FROM CTDATHANG
--SELECT * FROM CTDATHANG WHERE SOHD = 6